;; chain_full_footprint — GENERATED by gen_cache_miss_chain.py; do not edit.
;; dependent pointer-chase over a Sattolo single-cycle permutation.
;; N=10000 nodes, stride=64 B (footprint 640000 B), traverse 10000x.
;; Phases in finish: identity fill -> Sattolo shuffle -> chase (see gen).
;; Lifecycle: finish_removes (+accumulate)   Purpose: dos   Gas: 1000000
;; Expected EscrowFinish: tesSUCCESS. Measure time=/gas (memory-hierarchy).
;; 32-byte opaque_random seed slot at offset 0 (fresh permutation/cycle).
(module
  (memory 10)
  (data (i32.const 0) "\c4\11\ff\01\00\01\02\03\04\05\06\07\08\09\0a\0b\0c\0d\0e\0f\10\11\12\13\14\15\16\17\18\19\1a\1b")
  (func (export "escrow_finish") (result i32)
    (local $rng i32) (local $i i32) (local $j i32)
    (local $cur i32) (local $tmp i32) (local $ai i32) (local $aj i32)
    ;; seed xorshift from the patched slot; force nonzero
    (local.set $rng (i32.or (i32.load (i32.const 0)) (i32.const 1)))
    ;; phase 1: identity fill p[i]=i
    (local.set $i (i32.const 0))
    (loop $init
      (i32.store (i32.add (i32.const 64) (i32.mul (local.get $i) (i32.const 64))) (local.get $i))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $init (i32.lt_u (local.get $i) (i32.const 10000))))
    ;; phase 2: Sattolo shuffle -> a single random n-cycle
    (local.set $i (i32.const 9999))
    (block $done
      (loop $sat
        (br_if $done (i32.eqz (local.get $i)))
    (local.set $rng (i32.xor (local.get $rng) (i32.shl (local.get $rng) (i32.const 13))))
    (local.set $rng (i32.xor (local.get $rng) (i32.shr_u (local.get $rng) (i32.const 17))))
    (local.set $rng (i32.xor (local.get $rng) (i32.shl (local.get $rng) (i32.const 5))))
        (local.set $j (i32.rem_u (local.get $rng) (local.get $i)))
        (local.set $ai (i32.add (i32.const 64) (i32.mul (local.get $i) (i32.const 64))))
        (local.set $aj (i32.add (i32.const 64) (i32.mul (local.get $j) (i32.const 64))))
        (local.set $tmp (i32.load (local.get $ai)))
        (i32.store (local.get $ai) (i32.load (local.get $aj)))
        (i32.store (local.get $aj) (local.get $tmp))
        (local.set $i (i32.sub (local.get $i) (i32.const 1)))
        (br $sat)))
    ;; phase 3: dependent chase, T steps from node 0
    (local.set $cur (i32.const 0))
    (local.set $i (i32.const 0))
    (loop $trav
      (local.set $cur (i32.load (i32.add (i32.const 64) (i32.mul (local.get $cur) (i32.const 64)))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $trav (i32.lt_u (local.get $i) (i32.const 10000))))
    ;; return >0 (uses cur so the chase can't be dead-code-eliminated)
    (i32.or (local.get $cur) (i32.const 1))))
