;; chain_L1_resident — GENERATED by gen_cache_miss_chain.py; do not edit.
;; dependent pointer-chase over a full-period LCG single cycle.
;; N=2048 nodes, stride=4 B (footprint 8192 B), traverse 16384x.
;; Phase 1 sequential LCG build next[i]=(a*i+c)&mask; phase 2 chases it.
;; Lifecycle: finish_removes (+accumulate)   Purpose: dos   Gas: 1000000
;; Expected EscrowFinish: tesSUCCESS. Measure time=/gas (memory-hierarchy).
;; 32-byte opaque_random seed slot at offset 0 (fresh a,c each cycle).
(module
  (memory 1)
  (data (i32.const 0) "\c4\11\00\01\00\01\02\03\04\05\06\07\08\09\0a\0b\0c\0d\0e\0f\10\11\12\13\14\15\16\17\18\19\1a\1b")
  (func (export "escrow_finish") (result i32)
    (local $a i32) (local $c i32) (local $i i32) (local $cur i32)
    ;; a = seed[0] with a==1 (mod 4) and a!=1; c = seed[4] | 1 (odd)
    (local.set $a (i32.or (i32.and (i32.load (i32.const 0)) (i32.const 0xfffffffc)) (i32.const 1)))
    (if (i32.eq (local.get $a) (i32.const 1)) (then (local.set $a (i32.const 5))))
    (local.set $c (i32.or (i32.load (i32.const 4)) (i32.const 1)))
    ;; phase 1: sequential build next[i] = (a*i + c) & mask
    (local.set $i (i32.const 0))
    (loop $build
      (i32.store (i32.add (i32.const 64) (i32.mul (local.get $i) (i32.const 4)))
        (i32.and (i32.add (i32.mul (local.get $a) (local.get $i)) (local.get $c)) (i32.const 2047)))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $build (i32.lt_u (local.get $i) (i32.const 2048))))
    ;; phase 2: dependent chase, T steps from node 0
    (local.set $cur (i32.const 0))
    (local.set $i (i32.const 0))
    (loop $trav
      (local.set $cur (i32.load (i32.add (i32.const 64) (i32.mul (local.get $cur) (i32.const 4)))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $trav (i32.lt_u (local.get $i) (i32.const 16384))))
    ;; return >0 (uses cur so the chase can't be dead-code-eliminated)
    (i32.or (local.get $cur) (i32.const 1))))
