#!/usr/bin/env python3
"""inst_data — generate wats/inst_data.wat (+ .patchspec.json).

dos_expensive_instantiation sub-case 1 of 3 (see NOTES "expensive instantiation").

An active (data ...) segment sized near the 100 KB module cap, copied into linear
memory at instantiation, paired with a trivial finish() { return 1 }. Wasmi
charges ZERO fuel for the data-section copy (verified; see NOTES), and xrpld
re-instantiates the module on every EscrowFinish, so the copy cost is paid per
Finish while the attacker pays only the one-time Create fee (5 x wasm_bytes).
This isolates the memory-init copy cost at instantiation.

The whole data segment IS the opaque_random patch slot: a 32-byte magic prefix
(so build_patchmaps locates the slot exactly once) followed by zero fill; the
patcher (role opaque_random) rewrites all DATA_BYTES with fresh random bytes each
EscrowCreate, so every cycle's Bytecode is unique (defeats module dedup) at no
fuel cost. Initial memory is the minimum pages that hold the segment, to keep the
measured cost the data copy and not extra page zeroing.

DATA_BYTES defaults to 90000 (~90% of the 100 KB BytecodeSizeLimit); the .wasm is
that plus a small module header, comfortably under the cap. Report .wasm size and
Create fee.

    python3 gen_inst_data.py [DATA_BYTES]
"""
import json
import sys
from pathlib import Path

DATA_BYTES = int(sys.argv[1]) if len(sys.argv) > 1 else 90000
NAME = "inst_data"
HERE = Path(__file__).resolve().parent
WASM_PAGE = 65536

MAGIC = bytes([0x1D, 0x57, 0xDA, 0x7A]) + bytes(range(28))   # 32-byte locator


def wat_bytes(b: bytes) -> str:
    return "".join(f"\\{x:02x}" for x in b)


def main():
    assert DATA_BYTES >= len(MAGIC)
    data = MAGIC + bytes(DATA_BYTES - len(MAGIC))            # magic + zero fill
    pages = (DATA_BYTES + WASM_PAGE - 1) // WASM_PAGE        # minimum to fit
    wat = (
        f";; {NAME} — GENERATED by gen_{NAME}.py; do not edit.\n"
        f";; active (data ...) of {DATA_BYTES} bytes copied to linear memory at\n"
        ";;   instantiation (zero fuel); trivial finish. Isolates the memory-init\n"
        ";;   copy cost, paid per Finish (module re-instantiated every Finish).\n"
        ";; Lifecycle: finish_removes (+accumulate)   Purpose: dos   Gas: 10000\n"
        ";; Expected EscrowFinish: tesSUCCESS. Watch time= (instantiation-dominant).\n"
        ";; The whole data segment is one opaque_random patch slot (zero-fuel).\n"
        "(module\n"
        f"  (memory {pages})\n"
        f'  (data (i32.const 0) "{wat_bytes(data)}")\n'
        '  (func (export "escrow_finish") (result i32)\n'
        "    (i32.const 1)))\n"
    )
    (HERE / f"{NAME}.wat").write_text(wat)

    spec = {
        "template": NAME,
        "slots": [
            {"name": "pad", "sentinel": MAGIC.hex().upper(),
             "length": DATA_BYTES, "role": "opaque_random"}
        ],
    }
    (HERE / f"{NAME}.patchspec.json").write_text(json.dumps(spec, indent=2) + "\n")
    print(f"wrote {NAME}.wat + .patchspec.json "
          f"(DATA_BYTES={DATA_BYTES}, memory={pages} pages)")


if __name__ == "__main__":
    main()
