#!/usr/bin/env python3
"""dos_large_finish_looped — generate wats/dos_large_finish_looped.wat (+spec).

DoS cost-dimension probe 2 of 3 (see NOTES "large-wasm cost dimensions").

A small `escrow_finish` body wrapped in a hot loop: BODY_UNITS copies of the
same trivial unit `(local.set $acc (i32.add (local.get $acc) (i32.const 1)))`
per iteration, run ITERS times. Total EXECUTED work is BODY_UNITS*ITERS units,
comparable to dos_large_finish_linear's COUNT, but the loop body is TRANSLATED
only once (on first entry) and then executed ITERS times. So this shape
isolates per-executed-instruction cost with translation amortized away.

Compare its time_us/gas against dos_large_finish_linear: if looped is elevated,
execution dominates; if linear is elevated but looped is not, translation
dominates (reference anchor ~8.9 ns/gas; see NOTES).

Returns a constant 1 -> tesSUCCESS (escrow removed). opaque_random padding: a
32-byte zero-fuel (data ...) slot rewritten per cycle (see the linear
generator's docstring for why).

ITERS*BODY_UNITS is bounded only by the Gas allowance (the .wasm stays tiny), so
this is the one of the three not size-capped. Defaults ITERS=100,
BODY_UNITS=50 -> 5000 executed units, ~20000 executed instructions, matching the
linear default's order of magnitude.

    python3 gen_dos_large_finish_looped.py [ITERS] [BODY_UNITS]
"""
import json
import sys
from pathlib import Path

ITERS = int(sys.argv[1]) if len(sys.argv) > 1 else 100
BODY_UNITS = int(sys.argv[2]) if len(sys.argv) > 2 else 50
NAME = "dos_large_finish_looped"
HERE = Path(__file__).resolve().parent

SENTINEL = bytes([0xD0, 0x51, 0x00, 0x0F]) + bytes(range(28))


def wat_bytes(b: bytes) -> str:
    return "".join(f"\\{x:02x}" for x in b)


def main():
    unit = ("      (local.set $acc "
            "(i32.add (local.get $acc) (i32.const 1)))\n")
    loop_body = unit * BODY_UNITS
    wat = (
        f";; {NAME} — GENERATED by gen_{NAME}.py; do not edit.\n"
        f";; hot loop: {ITERS} iterations x {BODY_UNITS} trivial units; the loop\n"
        ";;   body is translated once and executed each iteration (execution\n"
        ";;   isolated, translation amortized).\n"
        ";; Lifecycle: finish_removes (+accumulate)   Purpose: dos   Gas: 1000000\n"
        ";; Expected EscrowFinish: tesSUCCESS. Watch time= vs gas= (see NOTES).\n"
        ";; The 32-byte (data ...) blob is an opaque_random patch slot (zero-fuel).\n"
        "(module\n"
        "  (memory 1)\n"
        f'  (data (i32.const 0) "{wat_bytes(SENTINEL)}")\n'
        '  (func (export "escrow_finish") (result i32)\n'
        "    (local $i i32)\n"
        "    (local $acc i32)\n"
        "    (loop $L\n"
        + loop_body
        + "      (local.set $i (i32.add (local.get $i) (i32.const 1)))\n"
        f"      (br_if $L (i32.lt_s (local.get $i) (i32.const {ITERS}))))\n"
        "    (i32.const 1)))\n"
    )
    (HERE / f"{NAME}.wat").write_text(wat)

    spec = {
        "template": NAME,
        "slots": [
            {"name": "pad", "sentinel": SENTINEL.hex().upper(),
             "role": "opaque_random"}
        ],
    }
    (HERE / f"{NAME}.patchspec.json").write_text(json.dumps(spec, indent=2) + "\n")
    print(f"wrote {NAME}.wat + .patchspec.json (ITERS={ITERS}, "
          f"BODY_UNITS={BODY_UNITS}, executed_units={ITERS * BODY_UNITS})")


if __name__ == "__main__":
    main()
