#!/usr/bin/env python3
"""dos_large_finish_many_helpers — generate the .wat (+spec).

DoS cost-dimension probe 3 of 3 (see NOTES "large-wasm cost dimensions").

`escrow_finish` calls N helper functions once each and sums their results. Each
helper first-call-translates and takes one function entry inside the single
Finish, so relative to dos_large_finish_linear (the SAME body instructions in one
function / one entry) the extra cost here is N × per-function-entry setup. The
time_us/gas gap between this case and linear isolates the per-function-entry cost
dimension (reference anchor ~8.9 ns/gas; see NOTES).

Each helper body is HELPER_UNITS copies of the same `(i32.const 1)(i32.add)` unit
that linear uses, so the two cases do IDENTICAL body work and the gap between them
is purely the entries. N_HELPERS × HELPER_UNITS is set to match linear's unit
count, so linear is the one-entry comparator.

xrpld guard (found live, 2026-10-01): the node rejects a module whose average
code-bytes-per-function is below 40 once total function bytes exceed 1000
(AvgBytesPerFunctionLimit{req_funcs_bytes:1000, min_avg_bytes_per_function:40} in
crates/xrpl-wasm-vm/src/vm.rs) — a defense against exactly the many-tiny-functions
translation-cost attack. An earlier version used 5000 one-instruction helpers
(avg 8 bytes) and was rejected temINVALID_BYTECODE ("minimum average bytes per
function of 40: avg=8"). HELPER_UNITS=20 gives ~62-byte helper bodies, clearing
the guard, and keeps the probe valid in the regime the guard permits.

opaque_random padding: a 32-byte zero-fuel (data ...) slot rewritten per cycle
(see the linear generator's docstring).

    python3 gen_dos_large_finish_many_helpers.py [N_HELPERS] [HELPER_UNITS]
"""
import json
import sys
from pathlib import Path

N_HELPERS = int(sys.argv[1]) if len(sys.argv) > 1 else 250
HELPER_UNITS = int(sys.argv[2]) if len(sys.argv) > 2 else 20
NAME = "dos_large_finish_many_helpers"
HERE = Path(__file__).resolve().parent

SENTINEL = bytes([0xD0, 0x51, 0x3E, 0x19]) + bytes(range(28))


def wat_bytes(b: bytes) -> str:
    return "".join(f"\\{x:02x}" for x in b)


def main():
    unit = "(i32.const 1) (i32.add) "
    body = unit * HELPER_UNITS          # HELPER_UNITS add-units -> sum = HELPER_UNITS
    helpers = "".join(
        f"  (func $h{i} (result i32) (i32.const 0) {body})\n" for i in range(N_HELPERS)
    )
    calls = "".join(
        f"    (local.set $acc (i32.add (local.get $acc) (call $h{i})))\n"
        for i in range(N_HELPERS)
    )
    total_units = N_HELPERS * HELPER_UNITS
    wat = (
        f";; {NAME} — GENERATED by gen_{NAME}.py; do not edit.\n"
        f";; escrow_finish calls {N_HELPERS} helpers once each, summing results;\n"
        f";;   each helper = {HELPER_UNITS} (i32.const 1)(i32.add) units (~62 B, over\n"
        ";;   the xrpld min-avg-40-bytes/function guard). Total body units\n"
        f";;   ({total_units}) match dos_large_finish_linear; the gap isolates the\n"
        ";;   per-function-ENTRY cost (N first-call translations + N entries).\n"
        ";; Lifecycle: finish_removes (+accumulate)   Purpose: dos   Gas: 1000000\n"
        ";; Expected EscrowFinish: tesSUCCESS. Watch time= vs gas= (see NOTES).\n"
        ";; The 32-byte (data ...) blob is an opaque_random patch slot (zero-fuel).\n"
        "(module\n"
        "  (memory 1)\n"
        f'  (data (i32.const 0) "{wat_bytes(SENTINEL)}")\n'
        + helpers
        + '  (func (export "escrow_finish") (result i32)\n'
        "    (local $acc i32)\n"
        + calls
        + "    (i32.or (local.get $acc) (i32.const 1))))\n"
    )
    (HERE / f"{NAME}.wat").write_text(wat)

    spec = {
        "template": NAME,
        "slots": [
            {"name": "pad", "sentinel": SENTINEL.hex().upper(),
             "role": "opaque_random"}
        ],
    }
    (HERE / f"{NAME}.patchspec.json").write_text(json.dumps(spec, indent=2) + "\n")
    print(f"wrote {NAME}.wat + .patchspec.json "
          f"(N_HELPERS={N_HELPERS}, HELPER_UNITS={HELPER_UNITS}, "
          f"total_units={total_units})")


if __name__ == "__main__":
    main()
