#!/usr/bin/env python3
"""cache_le_pattern TEMPLATE — generate wats/cache_le_pattern.wat + patchspec.

One template for the whole cache_le_pattern preset family (cache_miss_single,
cache_hit_single, cache_miss_storm, cache_hit_storm, cache_mixed_storm).
escrow_finish loops `count` times; each iteration takes one 20-byte account id
from a patched array, computes its AccountRoot keylet, and calls cache_le on it
(reusing slot 1, so every call does a fresh view().read of a distinct object —
the disk-read driver). Returns 1.

Two patch slots (filled per cycle by escrow_patch):
  count     4-byte LE iteration count (role u32_count)
  accounts  MAX_N * 20-byte account-id array (role account_id_array); the
            patcher fills the first `count` entries with a shuffled hit/miss
            mix (hits = distinct real accounts -> cache_le finds them; misses =
            random ids -> not found), the rest are unused filler.

Memory layout: [0]=count(4), [16]=account array(MAX_N*20), then a 32-byte
keylet scratch. MAX_N caps iterations; per iteration ~5350 gas (cache_le 5000 +
accountroot_id 350), so MAX_N*5350 must stay under the 1,000,000 GasLimit ->
MAX_N ~150.

    python3 gen_cache_le_pattern.py [MAX_N]
"""
import sys
from pathlib import Path

MAX_N = int(sys.argv[1]) if len(sys.argv) > 1 else 150
OUT = Path(__file__).resolve().parent / "cache_le_pattern.wat"
SPEC = Path(__file__).resolve().parent / "cache_le_pattern.patchspec.json"

COUNT_OFF = 0
ARRAY_OFF = 16
KEYLET_OUT = ARRAY_OFF + MAX_N * 20

COUNT_SENTINEL = "5AFEC0DE"                       # 4 bytes
ARRAY_SENTINEL = "ACCE55A2000102030405060708090A0B0C0D0E0F"  # 20 bytes


def esc(hexstr: str) -> str:
    return "".join(f"\\{hexstr[i:i+2].lower()}" for i in range(0, len(hexstr), 2))


def main():
    array_len = MAX_N * 20
    # array data: 20-byte sentinel to locate the region, then zero filler.
    array_bytes = esc(ARRAY_SENTINEL) + "\\00" * (array_len - 20)
    wat = f""";; cache_le_pattern — GENERATED by gen_cache_le_pattern.py (MAX_N={MAX_N}).
;; Loop `count` times: accountroot_id(account[i]) -> keylet -> cache_le(slot 1).
;; count and the account array are patch slots (see cache_le_pattern.patchspec.json).
(module
  (import "host_lib" "accountroot_id"
    (func $accountroot_id (param i32 i32 i32 i32) (result i32)))
  (import "host_lib" "cache_le"
    (func $cache_le (param i32 i32 i32) (result i32)))
  (memory (export "memory") 1)
  (data (i32.const {COUNT_OFF}) "{esc(COUNT_SENTINEL)}")
  (data (i32.const {ARRAY_OFF}) "{array_bytes}")
  (func (export "escrow_finish") (result i32)
    (local $i i32) (local $n i32) (local $ptr i32)
    (local.set $n (i32.load (i32.const {COUNT_OFF})))
    (block $done
      (loop $L
        (br_if $done (i32.ge_s (local.get $i) (local.get $n)))
        (local.set $ptr
          (i32.add (i32.const {ARRAY_OFF}) (i32.mul (local.get $i) (i32.const 20))))
        (drop (call $accountroot_id
          (local.get $ptr) (i32.const 20) (i32.const {KEYLET_OUT}) (i32.const 32)))
        (drop (call $cache_le (i32.const {KEYLET_OUT}) (i32.const 32) (i32.const 1)))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $L)))
    (i32.const 1)))
"""
    OUT.write_text(wat)
    spec = f"""{{
  "template": "cache_le_pattern",
  "slots": [
    {{"name": "count", "sentinel": "{COUNT_SENTINEL}", "role": "u32_count"}},
    {{"name": "accounts", "sentinel": "{ARRAY_SENTINEL}", "length": {array_len}, "role": "account_id_array"}}
  ]
}}
"""
    SPEC.write_text(spec)
    print(f"wrote {OUT} and {SPEC} (MAX_N={MAX_N}, array {array_len} bytes)")


if __name__ == "__main__":
    main()
