#!/usr/bin/env python3
"""dos_cache_miss_chain — generate the cache-miss pointer-chase presets.

The strongest known pure-wasm DoS shape: a data-dependent pointer chase over a
random permutation, so every load depends on the previous one (no memory-level
parallelism, no prefetch) and cost is set by the memory-hierarchy level the
working set falls into. Emits two presets from one template, differing only in
working-set size:

  chain_L1_resident     small dense array (~8 KB) that stays in L1; the warm-cache
                        floor. Traversed many passes for a stable measurement.
  chain_full_footprint  the largest array the 1M gas ceiling lets finish BUILD
                        in-wasm (~0.5-0.7 MB with Sattolo), traversed one pass so
                        every load is a fresh line. Named by shape, not "L3": on
                        our hosts (M4 Pro ~24 MB L3, Threadripper 9960X ~128 MB
                        L3) this footprint is an L2/LLC chase, NOT DRAM-evicting.
                        DRAM latency is unreachable here — the gas ceiling caps
                        the attacker's working set well below any modern LLC (see
                        NOTES "cache-miss chain").

finish() has three phases, all in linear memory (a fresh zeroed memory every
Finish, so it is rebuilt each time):
  1. identity fill:  p[i] = i for i in 0..N.
  2. Sattolo shuffle (a uniformly random SINGLE cycle / Hamiltonian permutation):
     for i = N-1 downto 1: j = rand() mod i; swap p[i], p[j]. Guarantees one
     n-cycle, so a one-pass traversal touches every node exactly once.
  3. traverse: cur = p[cur], T times. full_footprint uses T = N (one pass);
     L1_resident uses T >> N (many warm passes).
The xorshift32 PRNG is seeded from a 32-byte opaque_random slot at offset 0 that
the patcher rewrites every EscrowCreate, so each cycle gets a fresh permutation
(defeats per-address pattern learning across Finishes). No new patcher role —
the existing opaque_random role fills the seed.

Fuel note (wasmi 2.0.0, 1 fuel/operator): ~78 fuel per node (fill+Sattolo+one
traverse step), so N is gas-bounded to ~12K nodes under the 1M ceiling; that is
why full_footprint tops out sub-MB. Gas allowance is set to the 1M ceiling so the
loop runs as long as possible; WASM_TIMING time= (not gas) is the measurement.

    python3 gen_cache_miss_chain.py
"""
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
BASE = 64          # chain array starts here (past the 32-byte seed slot at 0)
WASM_PAGE = 65536

# name -> (N nodes, STRIDE bytes/node, T traversal steps, 32-byte magic prefix)
PRESETS = {
    "chain_L1_resident":    dict(N=2048,  STRIDE=4,  T=50000,
                                 magic=[0xC4, 0x11, 0x00, 0x01]),
    "chain_full_footprint": dict(N=10000, STRIDE=64, T=10000,
                                 magic=[0xC4, 0x11, 0xFF, 0x01]),
}


def wat_bytes(b: bytes) -> str:
    return "".join(f"\\{x:02x}" for x in b)


def addr(idx_expr: str, stride: int) -> str:
    return (f"(i32.add (i32.const {BASE}) "
            f"(i32.mul {idx_expr} (i32.const {stride})))")


def rng_update() -> str:
    # xorshift32: x^=x<<13; x^=x>>17; x^=x<<5
    return (
        "    (local.set $rng (i32.xor (local.get $rng) "
        "(i32.shl (local.get $rng) (i32.const 13))))\n"
        "    (local.set $rng (i32.xor (local.get $rng) "
        "(i32.shr_u (local.get $rng) (i32.const 17))))\n"
        "    (local.set $rng (i32.xor (local.get $rng) "
        "(i32.shl (local.get $rng) (i32.const 5))))\n"
    )


def build_wat(name: str, N: int, STRIDE: int, T: int, magic: list[int]) -> str:
    sentinel = bytes(magic) + bytes(range(28))          # 32-byte seed slot
    pages = (BASE + N * STRIDE + WASM_PAGE - 1) // WASM_PAGE
    footprint = N * STRIDE
    return (
        f";; {name} — GENERATED by gen_cache_miss_chain.py; do not edit.\n"
        f";; dependent pointer-chase over a Sattolo single-cycle permutation.\n"
        f";; N={N} nodes, stride={STRIDE} B (footprint {footprint} B), traverse {T}x.\n"
        ";; Phases in finish: identity fill -> Sattolo shuffle -> chase (see gen).\n"
        ";; Lifecycle: finish_removes (+accumulate)   Purpose: dos   Gas: 1000000\n"
        ";; Expected EscrowFinish: tesSUCCESS. Measure time=/gas (memory-hierarchy).\n"
        ";; 32-byte opaque_random seed slot at offset 0 (fresh permutation/cycle).\n"
        "(module\n"
        f"  (memory {pages})\n"
        f'  (data (i32.const 0) "{wat_bytes(sentinel)}")\n'
        '  (func (export "escrow_finish") (result i32)\n'
        "    (local $rng i32) (local $i i32) (local $j i32)\n"
        "    (local $cur i32) (local $tmp i32) (local $ai i32) (local $aj i32)\n"
        "    ;; seed xorshift from the patched slot; force nonzero\n"
        "    (local.set $rng (i32.or (i32.load (i32.const 0)) (i32.const 1)))\n"
        "    ;; phase 1: identity fill p[i]=i\n"
        "    (local.set $i (i32.const 0))\n"
        "    (loop $init\n"
        f"      (i32.store {addr('(local.get $i)', STRIDE)} (local.get $i))\n"
        "      (local.set $i (i32.add (local.get $i) (i32.const 1)))\n"
        f"      (br_if $init (i32.lt_u (local.get $i) (i32.const {N}))))\n"
        "    ;; phase 2: Sattolo shuffle -> a single random n-cycle\n"
        f"    (local.set $i (i32.const {N - 1}))\n"
        "    (block $done\n"
        "      (loop $sat\n"
        "        (br_if $done (i32.eqz (local.get $i)))\n"
        + rng_update()
        + "        (local.set $j (i32.rem_u (local.get $rng) (local.get $i)))\n"
        f"        (local.set $ai {addr('(local.get $i)', STRIDE)})\n"
        f"        (local.set $aj {addr('(local.get $j)', STRIDE)})\n"
        "        (local.set $tmp (i32.load (local.get $ai)))\n"
        "        (i32.store (local.get $ai) (i32.load (local.get $aj)))\n"
        "        (i32.store (local.get $aj) (local.get $tmp))\n"
        "        (local.set $i (i32.sub (local.get $i) (i32.const 1)))\n"
        "        (br $sat)))\n"
        "    ;; phase 3: dependent chase, T steps from node 0\n"
        "    (local.set $cur (i32.const 0))\n"
        "    (local.set $i (i32.const 0))\n"
        "    (loop $trav\n"
        f"      (local.set $cur (i32.load {addr('(local.get $cur)', STRIDE)}))\n"
        "      (local.set $i (i32.add (local.get $i) (i32.const 1)))\n"
        f"      (br_if $trav (i32.lt_u (local.get $i) (i32.const {T}))))\n"
        "    ;; return >0 (uses cur so the chase can't be dead-code-eliminated)\n"
        "    (i32.or (local.get $cur) (i32.const 1))))\n"
    )


def main():
    for name, p in PRESETS.items():
        wat = build_wat(name, p["N"], p["STRIDE"], p["T"], p["magic"])
        (HERE / f"{name}.wat").write_text(wat)
        spec = {
            "template": name,
            "slots": [
                {"name": "seed",
                 "sentinel": (bytes(p["magic"]) + bytes(range(28))).hex().upper(),
                 "role": "opaque_random"}
            ],
        }
        (HERE / f"{name}.patchspec.json").write_text(
            json.dumps(spec, indent=2) + "\n")
        pages = (BASE + p["N"] * p["STRIDE"] + WASM_PAGE - 1) // WASM_PAGE
        print(f"wrote {name}.wat + .patchspec.json "
              f"(N={p['N']}, stride={p['STRIDE']}, footprint={p['N']*p['STRIDE']}B, "
              f"T={p['T']}, memory={pages} pages)")


if __name__ == "__main__":
    main()
