#!/usr/bin/env python3
"""dos_large_finish_linear — generate wats/dos_large_finish_linear.wat (+spec).

DoS cost-dimension probe 1 of 3 (see NOTES "large-wasm cost dimensions").

One huge straight-line `escrow_finish` body: COUNT copies of a trivial data-flow
unit `(i32.const 1) (i32.add)` running on a single accumulator, no loops and no
branches. Every instruction is TRANSLATED on first entry (Wasmi lazy
translation) AND EXECUTED exactly once, so this shape sums per-instruction
translation cost + per-instruction execution cost. Compare its time_us/gas
against dos_large_finish_looped (execution only, translation amortized) and
dos_large_finish_many_helpers (adds per-function-entry cost) to see which Wasmi
cost dimension is underpriced (reference anchor ~8.9 ns/gas; see NOTES).

The accumulator sum (= COUNT) is left on the stack as the i32 result, so a
non-loop body still returns > 0 -> tesSUCCESS (escrow removed).

opaque_random padding: a 32-byte (data ...) slot, rewritten with fresh random
bytes every EscrowCreate by the patcher (role opaque_random). Data-section init
is charged ZERO fuel, so the padding makes each module's bytes unique (defeats
any module-store dedup keyed on identical Bytecode) WITHOUT distorting the
time_us/gas measurement.

COUNT caps two ways: the .wasm must stay under BytecodeSizeLimit (100 KB; each
unit is ~3 bytes) and the translate+execute cost must stay under the Gas
allowance so the Finish succeeds. Default 5000 (~15 KB) leaves wide margin under
both; raise it after the first live run calibrates the real cost.

    python3 gen_dos_large_finish_linear.py [COUNT]
"""
import json
import sys
from pathlib import Path

COUNT = int(sys.argv[1]) if len(sys.argv) > 1 else 5000
NAME = "dos_large_finish_linear"
HERE = Path(__file__).resolve().parent

# 32-byte opaque_random padding sentinel: a distinctive magic prefix + a
# monotonic tail, so build_patchmaps locates it exactly once in the .wasm.
SENTINEL = bytes([0xD0, 0x51, 0x1A, 0x17]) + bytes(range(28))


def wat_bytes(b: bytes) -> str:
    return "".join(f"\\{x:02x}" for x in b)


def main():
    unit = "    (i32.const 1) (i32.add)\n"
    body = unit * COUNT
    wat = (
        f";; {NAME} — GENERATED by gen_{NAME}.py; do not edit.\n"
        f";; straight-line escrow_finish: {COUNT} x (i32.const 1)(i32.add) on one\n"
        ";;   accumulator; each instruction translated AND executed once.\n"
        ";; Lifecycle: finish_removes (+accumulate)   Purpose: dos   Gas: 1000000\n"
        ";; Expected EscrowFinish: tesSUCCESS. Watch time= vs gas= (see NOTES).\n"
        ";; The 32-byte (data ...) blob is an opaque_random patch slot (zero-fuel).\n"
        "(module\n"
        "  (memory 1)\n"
        f'  (data (i32.const 0) "{wat_bytes(SENTINEL)}")\n'
        '  (func (export "escrow_finish") (result i32)\n'
        "    (i32.const 0)\n"
        + body
        + "  ))\n"
    )
    (HERE / f"{NAME}.wat").write_text(wat)

    spec = {
        "template": NAME,
        "slots": [
            {"name": "pad", "sentinel": SENTINEL.hex().upper(),
             "role": "opaque_random"}
        ],
    }
    (HERE / f"{NAME}.patchspec.json").write_text(json.dumps(spec, indent=2) + "\n")
    print(f"wrote {NAME}.wat + .patchspec.json (COUNT={COUNT}, "
          f"~{3 * COUNT // 1024} KB body)")


if __name__ == "__main__":
    main()
