#!/usr/bin/env python3
"""inst_locals — generate wats/inst_locals.wat (+ .patchspec.json).

dos_expensive_instantiation sub-case 3 of 3 (see NOTES "expensive instantiation").

escrow_finish declares LOCALS i32 locals near the wasmi per-function cap, with a
trivial body (return 1). Wasmi zeroes every declared local slot at function entry;
that per-frame slot-zeroing is charged zero fuel today, and xrpld enters finish
(re-instantiating the module) on every EscrowFinish, so the zeroing is paid per
Finish. This isolates the per-frame local-init cost.

We deliberately do NOT touch each local. Declared locals are frame-zeroed at
entry whether used or not, and wat2wasm never drops them, so the cost is already
paid; adding LOCALS x (local.get + drop) would inject ~2*LOCALS body instructions
that translate AND execute, making the wall-clock translation-dominant rather than
instantiation/entry-dominant (and would blow past the 100 KB size cap). Trivial
body keeps the measurement on the frame-init cost.

An upstream PR is in flight to charge fuel for per-frame local init; keep this as
a regression test — once it lands, time_us/gas here should drop.

LOCALS defaults to 30000, the wasmi hard cap (LocalsRegistry::LOCAL_VARIABLES_MAX
in wasmi 2.0.0 engine/translator/func/locals.rs; the check is strict-greater so
30000 itself is allowed; NOT the inert wasmparser/EnforcedLimits 50000). The
existing many_locals also sits at 30000 but calls a helper in a loop 100x; this
case declares them in finish itself and enters once, a cleaner single-entry probe.
A 32-byte opaque_random (data ...) pad keeps each cycle's Bytecode unique.

    python3 gen_inst_locals.py [LOCALS]
"""
import json
import sys
from pathlib import Path

LOCALS = int(sys.argv[1]) if len(sys.argv) > 1 else 30000
NAME = "inst_locals"
HERE = Path(__file__).resolve().parent

MAGIC = bytes([0x1D, 0x57, 0x10, 0xCA]) + bytes(range(28))   # 32-byte locator


def wat_bytes(b: bytes) -> str:
    return "".join(f"\\{x:02x}" for x in b)


def main():
    per_line = 50
    local_lines = []
    remaining = LOCALS
    while remaining > 0:
        k = min(per_line, remaining)
        local_lines.append("    (local " + " ".join(["i32"] * k) + ")")
        remaining -= k
    wat = (
        f";; {NAME} — GENERATED by gen_{NAME}.py; do not edit.\n"
        f";; escrow_finish declares {LOCALS} i32 locals (wasmi cap 30000), trivial\n"
        ";;   body. Every slot is zeroed at function entry (zero fuel today); paid\n"
        ";;   per Finish. Isolates per-frame local-init cost (regression test for\n"
        ";;   the in-flight fuel-charging PR). Locals are intentionally not used.\n"
        ";; Lifecycle: finish_removes (+accumulate)   Purpose: dos   Gas: 10000\n"
        ";; Expected EscrowFinish: tesSUCCESS. Watch time= (frame-init-dominant).\n"
        ";; 32-byte opaque_random pad (zero-fuel).\n"
        "(module\n"
        "  (memory 1)\n"
        f'  (data (i32.const 0) "{wat_bytes(MAGIC)}")\n'
        '  (func (export "escrow_finish") (result i32)\n'
        + "\n".join(local_lines) + "\n"
        "    (i32.const 1)))\n"
    )
    (HERE / f"{NAME}.wat").write_text(wat)

    spec = {
        "template": NAME,
        "slots": [
            {"name": "pad", "sentinel": MAGIC.hex().upper(),
             "role": "opaque_random"}
        ],
    }
    (HERE / f"{NAME}.patchspec.json").write_text(json.dumps(spec, indent=2) + "\n")
    print(f"wrote {NAME}.wat + .patchspec.json (LOCALS={LOCALS})")


if __name__ == "__main__":
    main()
