#!/usr/bin/env python3
"""D3 home_le_field_bytecode — generate wats/home_le_field_bytecode.wat.

escrow_finish reads its own sfBytecode field (code 47) via home_le_field into a
1 KB buffer, ITERS times. The host copies the whole (large) bytecode before
checking the 1 KB output limit, so each call returns DataFieldTooLarge (-12)
after an unaccounted copy (audit finding 3.11). The module is padded to
PAD_BYTES so its own sfBytecode is large enough for the copy to matter.

A generator, not a hand-written wat, because the padding is a multi-KB data
segment. Padding is inert (a data segment placed high in linear memory, never
read by the code).

    python3 gen_home_le_field_bytecode.py [PAD_BYTES] [ITERS]

Start: PAD_BYTES=30000, ITERS=100.
"""
import sys
from pathlib import Path

PAD_BYTES = int(sys.argv[1]) if len(sys.argv) > 1 else 30000
ITERS = int(sys.argv[2]) if len(sys.argv) > 2 else 100
OUT = Path(__file__).resolve().parent / "home_le_field_bytecode.wat"
PAD_OFFSET = 4096   # padding sits above the 1 KB read buffer at [0..1024]


def main():
    # One page = 65536 bytes; keep the buffer + padding inside it.
    assert PAD_OFFSET + PAD_BYTES < 65536, "padding exceeds one wasm page"
    pad = "\\11" * PAD_BYTES   # inert bytes, never read
    lines = [
        ";; D3 home_le_field_bytecode — GENERATED by gen_home_le_field_bytecode.py.",
        f";; reads own sfBytecode (code 458799) {ITERS}x; module padded to ~{PAD_BYTES} bytes.",
        ";; Lifecycle: finish_removes   Gas: 20000",
        ";; Expected EscrowFinish: tesSUCCESS (each read returns",
        ";;   DataFieldTooLarge -12, ignored). Watch time= vs gas= (audit 3.11).",
        "(module",
        '  (import "host_lib" "home_le_field"',
        "    (func $hlf (param i32 i32 i32) (result i32)))",
        '  (memory (export "memory") 1)',
        f'  (data (i32.const {PAD_OFFSET}) "{pad}")',
        '  (func (export "escrow_finish") (result i32)',
        "    (local $i i32)",
        "    (loop $L",
        "      (drop (call $hlf",
        "        (i32.const 47)     ;; sfBytecode field code",
        "        (i32.const 0)      ;; out_ptr",
        "        (i32.const 1024))) ;; out_len = 1 KB",
        "      (local.set $i (i32.add (local.get $i) (i32.const 1)))",
        f"      (br_if $L (i32.lt_s (local.get $i) (i32.const {ITERS}))))",
        "    (i32.const 1)))",
    ]
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT} (PAD_BYTES={PAD_BYTES}, ITERS={ITERS})")


if __name__ == "__main__":
    main()
