#!/usr/bin/env python3
"""D2 many_locals — generate wats/many_locals.wat.

A helper function that declares LOCALS i32 locals; escrow_finish calls it in a
loop of ITERS. Each call zeroes LOCALS slots, so wall time is disproportionate
to the gas charged (audit finding 3.9). The helper does nothing else and
returns 0.

    python3 gen_many_locals.py [LOCALS] [ITERS]

Start: LOCALS=30000, ITERS=100. Gas allowance tuned separately; report.
"""
import sys
from pathlib import Path

LOCALS = int(sys.argv[1]) if len(sys.argv) > 1 else 30000
ITERS = int(sys.argv[2]) if len(sys.argv) > 2 else 100
OUT = Path(__file__).resolve().parent / "many_locals.wat"


def main():
    # 30000 locals as ten-per-line (local i32 i32 ... ) groups keeps the text
    # readable and small; wat2wasm collapses them into one local-count anyway.
    per_line = 50
    local_lines = []
    remaining = LOCALS
    while remaining > 0:
        k = min(per_line, remaining)
        local_lines.append("    (local " + " ".join(["i32"] * k) + ")")
        remaining -= k
    lines = [
        ";; D2 many_locals — GENERATED by gen_many_locals.py; do not edit.",
        f";; helper with {LOCALS} i32 locals, called {ITERS}x per Finish.",
        ";; Lifecycle: finish_removes   Gas: 100000",
        ";; Expected EscrowFinish: tesSUCCESS. Watch time= vs gas= (audit 3.9).",
        "(module",
        "  (func $helper (result i32)",
        *local_lines,
        "    (i32.const 0))",
        '  (func (export "escrow_finish") (result i32)',
        "    (local $i i32)",
        "    (loop $L",
        "      (drop (call $helper))",
        "      (local.set $i (i32.add (local.get $i) (i32.const 1)))",
        f"      (br_if $L (i32.lt_s (local.get $i) (i32.const {ITERS}))))",
        "    (i32.const 1)))",
    ]
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT} (LOCALS={LOCALS}, ITERS={ITERS})")


if __name__ == "__main__":
    main()
