#!/usr/bin/env python3
"""inst_elem — generate wats/inst_elem.wat (+ .patchspec.json).

dos_expensive_instantiation sub-case 2 of 3 (see NOTES "expensive instantiation").

Declares (table ELEMENTS funcref) at the xrpld table cap and an active elem
segment that fills every entry, paired with a trivial finish() { return 1 }. The
finish does NOT call any table entry — this tests instantiation, not
call_indirect. Wasmi materializes every table entry inside instantiate_and_start,
before the guest's first instruction, at zero fuel; the xrpld source flags this
exact shape (crates/xrpl-wasm-vm/src/vm.rs, MAX_TABLE_ELEMENTS comment). xrpld
re-instantiates per Finish, so the 1024 materializations are paid every Finish.

One no-op dummy function is enough: an elem segment is a list of function indices
that may repeat, and wasmi materializes each of the ELEMENTS slots regardless of
which function it points at. So N dummy functions required = 1, referenced
ELEMENTS times. (Distinct dummies would only bloat the module and approach the
100 KB size cap for no extra materialization.)

A separate 32-byte opaque_random (data ...) pad keeps each cycle's Bytecode
unique (zero-fuel; see the inst_data generator).

ELEMENTS defaults to 1024 (the MAX_TABLE_ELEMENTS cap; the check is strict-greater
so the cap value itself is allowed). Report N and the resulting .wasm size.

    python3 gen_inst_elem.py [ELEMENTS]
"""
import json
import sys
from pathlib import Path

ELEMENTS = int(sys.argv[1]) if len(sys.argv) > 1 else 1024
NAME = "inst_elem"
HERE = Path(__file__).resolve().parent

MAGIC = bytes([0x1D, 0x57, 0xE1, 0xE1]) + bytes(range(28))   # 32-byte locator


def wat_bytes(b: bytes) -> str:
    return "".join(f"\\{x:02x}" for x in b)


def main():
    # One dummy function; the elem segment references it ELEMENTS times.
    refs = ("$d " * ELEMENTS).strip()
    wat = (
        f";; {NAME} — GENERATED by gen_{NAME}.py; do not edit.\n"
        f";; (table {ELEMENTS} funcref) with an elem segment filling every entry\n"
        ";;   (all -> one no-op dummy). Wasmi materializes every table entry at\n"
        ";;   instantiation (zero fuel), before finish runs; trivial finish, no\n"
        ";;   call_indirect. Isolates table-materialization cost, paid per Finish.\n"
        ";; Lifecycle: finish_removes (+accumulate)   Purpose: dos   Gas: 10000\n"
        ";; Expected EscrowFinish: tesSUCCESS. Watch time= (instantiation-dominant).\n"
        ";; N dummy functions required = 1. 32-byte opaque_random pad (zero-fuel).\n"
        "(module\n"
        f"  (table {ELEMENTS} funcref)\n"
        "  (func $d)\n"
        f"  (elem (i32.const 0) {refs})\n"
        "  (memory 1)\n"
        f'  (data (i32.const 0) "{wat_bytes(MAGIC)}")\n'
        '  (func (export "escrow_finish") (result i32)\n'
        "    (i32.const 1)))\n"
    )
    (HERE / f"{NAME}.wat").write_text(wat)

    spec = {
        "template": NAME,
        "slots": [
            {"name": "pad", "sentinel": MAGIC.hex().upper(),
             "role": "opaque_random"}
        ],
    }
    (HERE / f"{NAME}.patchspec.json").write_text(json.dumps(spec, indent=2) + "\n")
    print(f"wrote {NAME}.wat + .patchspec.json "
          f"(ELEMENTS={ELEMENTS}, dummy_functions=1)")


if __name__ == "__main__":
    main()
