#!/usr/bin/env python3
"""B3 oog_compile — generate wats/oog_compile.wat.

A module whose *translation* (compile) fuel is exhausted, a distinct out-of-gas
path from B2's execute-OOG (audit finding 3.4).

Wasmi uses CompilationMode::LazyTranslation: a function is translated (and
charged) only the first time it is CALLED, and unreferenced functions are never
translated. An earlier version left the noise functions uncalled, so they cost
nothing (gas=30). This version makes escrow_finish call every noise function so
each full body is translated, while a leading `return` keeps EXECUTION trivial:
the large body after it is unreachable at run time but is still translated on
first entry. So the gas charged is dominated by translation, not execution.

N noise functions, each `(return 0)` then BODY dead (i32.const 0)(drop) pairs.
Start: N=200, BODY=100. If it does not OOG at the category's Gas allowance,
raise N or BODY and rebuild. Report what worked.

    python3 gen_oog_compile.py [N] [BODY]
"""
import sys
from pathlib import Path

N = int(sys.argv[1]) if len(sys.argv) > 1 else 200
BODY = int(sys.argv[2]) if len(sys.argv) > 2 else 100
OUT = Path(__file__).resolve().parent / "oog_compile.wat"


def main():
    pair = "    (i32.const 0) (drop)\n"
    lines = [
        ";; B3 oog_compile — GENERATED by gen_oog_compile.py; do not edit.",
        f";; N={N} functions, each: (return 0) then {BODY} dead (const)(drop)",
        ";;   pairs. escrow_finish calls them all, forcing lazy translation of",
        ";;   every full body while execution stays trivial (early return).",
        ";; Lifecycle: cancel_removes   Gas: 1000",
        ";; Expected EscrowFinish: placeholder (translation-OOG; likely",
        ";;   tecOUT_OF_GAS / tecFAILED_PROCESSING). Report the actual code.",
        "(module",
    ]
    for i in range(N):
        lines.append(f"  (func $noise{i} (result i32)")
        # Early return keeps execution O(1); the dead body still translates.
        lines.append("    (return (i32.const 0))")
        lines.append("  " + pair * BODY + "    (i32.const 0))")
    lines.append('  (func (export "escrow_finish") (result i32)')
    for i in range(N):
        lines.append(f"    (drop (call $noise{i}))")
    lines.append("    (i32.const 1))")
    lines.append(")")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT} (N={N}, BODY={BODY})")


if __name__ == "__main__":
    main()
