#!/usr/bin/env python3
"""dos_large_finish_many_helpers — generate the .wat (+spec).

DoS cost-dimension probe 3 of 3 (see NOTES "large-wasm cost dimensions").

`escrow_finish` calls N tiny helper functions in sequence: helper_1(),
helper_2(), ..., helper_N(), dropping each result, then returns 1. Each helper
has a minimal one-instruction body (i32.const 1) and is called exactly once, so
each triggers its OWN first-call lazy translation inside the single Finish
invocation and one function entry. Relative to dos_large_finish_linear (the same
scale of instructions inside ONE function / one entry), the extra cost here is
N x (per-function-entry setup + per-tiny-body translation). So an elevation of
this shape over linear isolates the per-function-entry cost dimension.

Compare its time_us/gas against linear and looped (reference anchor
~8.9 ns/gas; see NOTES). Returns 1 -> tesSUCCESS (escrow removed).

opaque_random padding: a 32-byte zero-fuel (data ...) slot rewritten per cycle
(see the linear generator's docstring).

N caps by BytecodeSizeLimit (100 KB): each helper + its call site is ~12 bytes,
so N ~ 8000 is the ceiling. Default 5000 (~60 KB) matches the linear default's
instruction scale with margin under the limit.

    python3 gen_dos_large_finish_many_helpers.py [N]
"""
import json
import sys
from pathlib import Path

N = int(sys.argv[1]) if len(sys.argv) > 1 else 5000
NAME = "dos_large_finish_many_helpers"
HERE = Path(__file__).resolve().parent

SENTINEL = bytes([0xD0, 0x51, 0x3E, 0x19]) + bytes(range(28))


def wat_bytes(b: bytes) -> str:
    return "".join(f"\\{x:02x}" for x in b)


def main():
    helpers = "".join(
        f'  (func $h{i} (result i32) (i32.const 1))\n' for i in range(N)
    )
    calls = "".join(
        f"    (drop (call $h{i}))\n" for i in range(N)
    )
    wat = (
        f";; {NAME} — GENERATED by gen_{NAME}.py; do not edit.\n"
        f";; escrow_finish calls {N} tiny helper fns once each; every helper\n"
        ";;   first-call-translates + one function entry inside the one Finish.\n"
        ";; Lifecycle: finish_removes (+accumulate)   Purpose: dos   Gas: 1000000\n"
        ";; Expected EscrowFinish: tesSUCCESS. Watch time= vs gas= (see NOTES).\n"
        ";; The 32-byte (data ...) blob is an opaque_random patch slot (zero-fuel).\n"
        "(module\n"
        "  (memory 1)\n"
        f'  (data (i32.const 0) "{wat_bytes(SENTINEL)}")\n'
        + helpers
        + '  (func (export "escrow_finish") (result i32)\n'
        + calls
        + "    (i32.const 1)))\n"
    )
    (HERE / f"{NAME}.wat").write_text(wat)

    spec = {
        "template": NAME,
        "slots": [
            {"name": "pad", "sentinel": SENTINEL.hex().upper(),
             "role": "opaque_random"}
        ],
    }
    (HERE / f"{NAME}.patchspec.json").write_text(json.dumps(spec, indent=2) + "\n")
    print(f"wrote {NAME}.wat + .patchspec.json (N={N} helpers)")


if __name__ == "__main__":
    main()
