#!/usr/bin/env python3
"""B3 oog_compile — generate wats/oog_compile.wat.

A module whose *translation* (compile) fuel is exhausted on Finish, a distinct
out-of-gas path from B2's execute-OOG (audit finding 3.4).

Wasmi uses CompilationMode::LazyTranslation: a function is translated (and
charged) the first time it is entered, before it runs. So escrow_finish's OWN
body is made huge — PAIRS copies of (i32.const 0)(drop) then `return 1` — and
translating that body on entry exhausts the Gas allowance before a single body
instruction executes. WASM_TIMING_FINISH shows tecOUT_OF_GAS with gas=0 (no
execution happened), which is how translation-OOG reads apart from execute-OOG.

(Earlier versions used many small helper functions; one huge finish body is
simpler and puts the cost squarely on the function actually entered.)

PAIRS caps two ways: the .wasm must stay under BytecodeSizeLimit (100 KB; each
pair is ~3 bytes) and big enough to OOG at the category's Gas (1000). Default
20000 (~60 KB) reliably OOGs at gas=1000 on the branch (see NOTES).

    python3 gen_oog_compile.py [PAIRS]
"""
import sys
from pathlib import Path

PAIRS = int(sys.argv[1]) if len(sys.argv) > 1 else 20000
OUT = Path(__file__).resolve().parent / "oog_compile.wat"


def main():
    body = "    (i32.const 0) (drop)\n" * PAIRS
    wat = (
        ";; B3 oog_compile — GENERATED by gen_oog_compile.py; do not edit.\n"
        f";; escrow_finish body = {PAIRS} (i32.const 0)(drop) pairs; translating\n"
        ";;   it on first entry exhausts the Gas allowance (translation-OOG).\n"
        ";; Lifecycle: cancel_removes   Gas: 1000\n"
        ";; Expected EscrowFinish: tecOUT_OF_GAS (gas=0 in WASM_TIMING_FINISH).\n"
        "(module\n"
        '  (func (export "escrow_finish") (result i32)\n'
        "    (return (i32.const 1))\n"
        + body
        + "    (i32.const 1)))\n"
    )
    OUT.write_text(wat)
    print(f"wrote {OUT} (PAIRS={PAIRS})")


if __name__ == "__main__":
    main()
